name: ci

on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: khainezayye
          password: Hp206164$
      -
        name: Build and push
        run: docker build --secret id=mysecret,src=secret-file . khainezayye/kzmodify && docker push khainezayye/kzmodify
